### PR TITLE
search working, bar fixed on top

### PR DESCRIPTION
**Pull request by pooja335**

### CODE REVIEW

**Comment by pooja335** [comment]
So my phone is having a weird rendering issue where if you search, and there's no results, and you keep typing, it won't show what you're typing until you make the keyboard go away. It works fine on my friend's iPhone though, and also on a different friend's LG G3. So if you guys aren't having this issue, then I think it's fine

**Comment by katsuya94** [comment]
I'm having the same problem. I think fixing it is necessary, but I couldn't figure out the cause with my initial investigation.

**Comment by pooja335** [comment]
Ok. My thought is that it has to do with something native in Android, since there's no js errors and from the html, it looks like it should be working

**Comment by katsuya94** [comment]
Maybe try using the underscore debounce. Less convenient, but it might magically work?

**Comment by pooja335** [comment]
Ok, so rather than using angular's filter in the html, I used it in the javascript (along with ng-keyup), to see if that would allow me to customize it (the rendering and/or debouncing) to fix the rendering issue. It didn't. Then, I used underscore's debounce to further try to customize it to fix it. Still didn't solve the issue. Tried a couple of random android chromium webview things, none of which worked. Finally, turns out it was related to the searchbar being position: fixed. So I made it unfixed, but I liked it being fixed, so I tried doing various overflow: scroll and height things, which kind of worked, but made the scrolling choppy and slow. I also tried using flexbox to set the height (w/o having to hardcode it) but it didn't work, and also kept it choppy and slow to scroll. So finally I decided to just let it scroll and not be fixed to the top, which fixed all the bugs and makes the loading and scrolling really smooth. It isn't fixed, but it works well otherwise.

**Comment by pooja335** [comment]
The reason for the super long comment above is that I've tried a bunch of stuff so I think we should just merge it in and move on to user testing.

**Comment by kapil1garg** [comment]
LGTM, seems to have fixed that weird bug of the nav bar getting locked and scroll up for me.

**Pull request merged**
